# Generated by Django 4.1.6 on 2023-03-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homes", "0014_alter_dayshift_occupancy"),
        ("users", "0002_auto_20230208_1025"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=100)),
                ("created", models.DateTimeField()),
                ("description", models.CharField(max_length=100)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applog",
                        to="homes.home",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applog",
                        to="users.bondableuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
