# Generated by Django 4.1.6 on 2023-03-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20230208_1025"),
        ("homes", "0014_alter_dayshift_occupancy"),
        ("applog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applog",
            name="user",
        ),
        migrations.AddField(
            model_name="applog",
            name="appuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userapplogs",
                to="users.bondableuser",
            ),
        ),
        migrations.AddField(
            model_name="applog",
            name="in_charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.bondableuser",
            ),
        ),
        migrations.AlterField(
            model_name="applog",
            name="data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applog",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homes.home"
            ),
        ),
    ]
