# Generated by Django 4.1.6 on 2023-07-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_alter_dayshift_occupancy'),
        ('applog', '0002_remove_applog_user_applog_appuser_applog_in_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applog',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homes.home'),
        ),
    ]
