# Generated by Django 4.1.6 on 2023-07-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230208_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bondableuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='bondableuser',
            name='name',
        ),
    ]
