version: "3.7"

services:
  api: &api
    platform: linux/amd64/v8
    build:
      context: "."
    image: bondable-backend-api
    container_name: bondable-backend-api-local
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      DD_AGENT_HOST: none
    env_file:
      - .config/.env
    ports:
      - 5000:5000
    command:
      - sh
      - -c
      - |
        sh /app/run.sh
    networks:
      bondable:

  postgres:
    image: library/postgres:14
    container_name: bondable-backend-postgres
    volumes:
      - bondable-backend-postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5433:5432
    env_file:
      - .config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      bondable:

  redis:
    image: redis:latest
    container_name: bondable-backend-redis
    expose:
      - 6379
    ports:
      - 6379:6379
    env_file:
      - .config/.env
    networks:
      bondable:

  redis-insights:
    image: redislabs/redisinsight:latest
    container_name: bondable-backend-redis-insights
    ports:
      - 8001:8001
    networks:
      bondable:

networks:
  bondable:
    name: bondable

volumes:
  bondable-backend-postgres:
