"""use new migrations for fk

Revision ID: 4fc10c3e2fce
Revises: 11aeb7a6aa29
Create Date: 2023-02-07 16:27:19.613796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc10c3e2fce'
down_revision = '11aeb7a6aa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
