"""use new migrations for fk

Revision ID: c5ce5708e2ec
Revises: eb321b4135f2
Create Date: 2023-02-07 14:41:13.719008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ce5708e2ec'
down_revision = 'eb321b4135f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
