"""use new migrations for fk

Revision ID: eb321b4135f2
Revises: 1b55d7a89634
Create Date: 2023-02-07 14:39:40.047930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb321b4135f2'
down_revision = '1b55d7a89634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_location_id'), 'location', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_location_id'), 'location', type_='unique')
    # ### end Alembic commands ###
