"""use new migrations for fk

Revision ID: 11aeb7a6aa29
Revises: ad250b415012
Create Date: 2023-02-07 16:26:56.359950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11aeb7a6aa29'
down_revision = 'ad250b415012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_location_id'), 'location', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_location_id'), 'location', type_='unique')
    # ### end Alembic commands ###
