# Generated by Django 3.1.8 on 2023-02-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active_beds', models.IntegerField(blank=True, null=True)),
                ('admissions', models.IntegerField(blank=True, null=True)),
                ('discharges', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('live_enquiries', models.IntegerField(blank=True, null=True)),
                ('hours_worked_from_home_in_last_24_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agency_hours_in_last_24_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('registered_beds', models.IntegerField(blank=True, null=True)),
                ('effective_beds', models.IntegerField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyShiftAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('planned_admissions', models.IntegerField(blank=True, null=True)),
                ('planned_discharges', models.IntegerField(blank=True, null=True)),
                ('expected_end_of_life', models.IntegerField(blank=True, null=True)),
                ('agency_nurse_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agency_senior_carer_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agency_carer_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_aggregates', to='homes.home')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyShiftAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('nurse_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carer_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_aggregates', to='homes.home')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
