# Generated by Django 4.1.6 on 2023-02-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20230208_1025"),
        ("homes", "0003_alter_dayshift_id_alter_home_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="lead_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.bondableuser",
            ),
        ),
    ]
