# Generated by Django 4.1.6 on 2023-02-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0004_home_lead_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyshiftaggregate",
            name="month",
            field=models.CharField(max_length=12),
        ),
    ]
