# Generated by Django 4.1.6 on 2023-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0005_alter_monthlyshiftaggregate_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyshiftaggregate",
            name="occupancy",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weeklyshiftaggregate",
            name="occupancy",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weeklyshiftaggregate",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
