# Generated by Django 4.1.6 on 2023-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0006_monthlyshiftaggregate_occupancy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyshiftaggregate",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
