# Generated by Django 4.1.6 on 2023-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0007_alter_monthlyshiftaggregate_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayshift",
            name="ASPS_in_last_24_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayshift",
            name="hours_worked",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dayshift",
            name="incidents_in_last_24_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
