# Generated by Django 4.1.6 on 2023-02-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0008_dayshift_asps_in_last_24_hours_dayshift_hours_worked_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayshift",
            old_name="location",
            new_name="home",
        ),
    ]
