# Generated by Django 4.1.6 on 2023-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0009_rename_location_dayshift_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dayshift",
            name="active_beds",
        ),
        migrations.AddField(
            model_name="dayshift",
            name="occupancy_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
