# Generated by Django 4.1.6 on 2023-02-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0010_remove_dayshift_active_beds_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dayshift",
            old_name="admissions",
            new_name="admissions_week_to_date",
        ),
        migrations.RenameField(
            model_name="dayshift",
            old_name="deaths",
            new_name="deaths_week_to_date",
        ),
        migrations.RenameField(
            model_name="dayshift",
            old_name="discharges",
            new_name="discharges_week_to_date",
        ),
    ]
