# Generated by Django 4.1.6 on 2023-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0011_rename_admissions_dayshift_admissions_week_to_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayshift",
            name="agency_hours_in_last_24_hours_carer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dayshift",
            name="agency_hours_in_last_24_hours_nurse",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dayshift",
            name="agency_hours_in_last_24_hours_senior_carer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
